add full script

diff --git a/.github/workflows/housekeeping.yml b/.github/workflows/housekeeping.yml
--- a/.github/workflows/housekeeping.yml
+++ b/.github/workflows/housekeeping.yml
@@ -30,3 +30,12 @@ jobs:
           find src/ \( -name "*.hpp" -o -name "*.cpp" -o -name "*.hh" -o -name "*.cc" -o -name "*.h" \) \
               \( -not -path "src/gtest*" -not -path "src/mcnp/mcnp?/Source/*" -not -path "src/pyne*" \)  \
               -exec clang-format -style=file -i {} \;
+          clang_diffs=`git status --porcelain`
+          if [ -z "${clang_diffs}" ]; then
+            echo "Style guide checker passed!"
+          else
+            echo "ERROR: Style guide checker failed. Please run clang-format."
+            echo "clang_diffs: ${clang_diffs}"
+            git diff
+            exit 1
+          fi
